"""Stage 15: construction plan -> deterministic Blender Python script.

`generate_blender_script` is a pure function of the plan: for a given
ConstructionPlan it always emits byte-identical script text. The generated
script runs inside Blender background mode and builds a named, hierarchical,
non-destructive scene, then exports scene.blend / model.glb and writes a
blender_manifest.json describing everything it created.

The generated script deliberately avoids: subprocess/shell, network,
eval/exec, ctypes, and any file access outside the paths handed to it via
argv after ``--`` (project_dir, blend path, glb path, manifest path).
"""
from __future__ import annotations

import json
from pathlib import Path

from .schemas import ConstructionPlan
from .config import PipelineConfig


# The generated script. Keep free of banned tokens (see runner.BANNED_TOKENS):
# no os.system / subprocess / socket / urllib / requests / shutil.rmtree /
# eval( / exec( / __import__ / ctypes.
_SCRIPT_TEMPLATE = '''\
# Auto-generated by recon3d.blender_codegen. Do not edit by hand.
import json
import math
import os
import sys

import bpy
from mathutils import Matrix, Vector
from mathutils.geometry import tessellate_polygon

ARGV = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else sys.argv[1:]
PROJECT_DIR = os.path.abspath(ARGV[0])
BLEND_PATH = ARGV[1]
GLB_PATH = ARGV[2]
MANIFEST_PATH = ARGV[3]

PLAN = json.loads(__PLAN_JSON__)

RENDER_ENGINE = __RENDER_ENGINE__

SEGMENTS = 48          # revolve / cylinder radial resolution
errors = []
notes = []


# --------------------------------------------------------------------------
# scene reset / units
# --------------------------------------------------------------------------

def reset_scene():
    bpy.ops.wm.read_factory_settings(use_empty=True)
    scene = bpy.context.scene
    scene.unit_settings.system = 'METRIC'
    scene.unit_settings.scale_length = 1.0   # 1 object unit = 1 m
    try:
        scene.render.engine = RENDER_ENGINE
    except Exception:
        scene.render.engine = 'BLENDER_EEVEE'
    return scene


# --------------------------------------------------------------------------
# materials (one shared material per unique spec)
# --------------------------------------------------------------------------

_materials = {}


def get_material(spec):
    key = (
        spec.get("material_class", "plastic"),
        tuple(round(float(c), 5) for c in spec.get("base_color", (0.8, 0.8, 0.8))),
        round(float(spec.get("roughness", 0.5)), 4),
        round(float(spec.get("metallic", 0.0)), 4),
        round(float(spec.get("opacity", 1.0)), 4),
        round(float(spec.get("transmission", 0.0)), 4),
    )
    if key in _materials:
        return _materials[key]
    name = "mat_%s_%02d" % (key[0], len(_materials))
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes.get("Principled BSDF")
    r, g, b = key[1]
    bsdf.inputs["Base Color"].default_value = (r, g, b, 1.0)
    bsdf.inputs["Roughness"].default_value = key[2]
    bsdf.inputs["Metallic"].default_value = key[3]
    if "Transmission Weight" in bsdf.inputs:
        bsdf.inputs["Transmission Weight"].default_value = key[5]
    if "Alpha" in bsdf.inputs:
        bsdf.inputs["Alpha"].default_value = key[4]
    if key[4] < 1.0:
        try:
            mat.surface_render_method = 'DITHERED'
        except Exception:
            try:
                mat.blend_method = 'BLEND'
            except Exception:
                pass
    mat.diffuse_color = (r, g, b, key[4])
    _materials[key] = mat
    return mat


# --------------------------------------------------------------------------
# mesh builders (geometry centred on the local origin = part pivot)
# --------------------------------------------------------------------------

def _new_mesh_object(name, verts, faces, collection):
    mesh = bpy.data.meshes.new(name + "_mesh")
    mesh.from_pydata(verts, [], faces)
    mesh.validate(clean_customdata=False)
    mesh.update()
    obj = bpy.data.objects.new(name, mesh)
    collection.objects.link(obj)
    return obj


def _axis_basis(direction):
    d = Vector(direction).normalized()
    ref = Vector((0.0, 0.0, 1.0)) if abs(d.z) < 0.9 else Vector((1.0, 0.0, 0.0))
    b1 = d.cross(ref).normalized()
    b2 = d.cross(b1).normalized()
    return d, b1, b2


def build_revolve(name, part, collection):
    profile = (part.get("profile") or {}).get("points") or []
    if len(profile) < 2:
        raise ValueError("revolve part %s needs >=2 profile points" % part.get("id"))
    axis = part.get("axis") or {}
    origin = Vector(axis.get("origin", [0.0, 0.0, 0.0]))
    d, b1, b2 = _axis_basis(axis.get("direction", [0.0, 0.0, 1.0]))
    closed_profile = bool((part.get("profile") or {}).get("closed", False))
    pts = [(float(p[0]), float(p[1])) for p in profile]
    verts = []
    rings = []
    for (r, h) in pts:
        if abs(r) < 1e-9:
            rings.append([len(verts)])
            verts.append(tuple(origin + d * h))
        else:
            ring = []
            for i in range(SEGMENTS):
                a = 2.0 * math.pi * i / SEGMENTS
                p = origin + d * h + (b1 * math.cos(a) + b2 * math.sin(a)) * r
                ring.append(len(verts))
                verts.append(tuple(p))
            rings.append(ring)
    faces = []
    for j in range(len(rings) - 1):
        ra, rb = rings[j], rings[j + 1]
        if len(ra) == 1 and len(rb) == 1:
            continue
        if len(ra) == 1:
            for i in range(SEGMENTS):
                faces.append((ra[0], rb[(i + 1) % SEGMENTS], rb[i]))
        elif len(rb) == 1:
            for i in range(SEGMENTS):
                faces.append((rb[0], ra[i], ra[(i + 1) % SEGMENTS]))
        else:
            for i in range(SEGMENTS):
                i2 = (i + 1) % SEGMENTS
                faces.append((ra[i], rb[i], rb[i2], ra[i2]))
    if closed_profile and len(rings) > 1 and len(rings[0]) == SEGMENTS and len(rings[-1]) == SEGMENTS:
        ra, rb = rings[-1], rings[0]
        for i in range(SEGMENTS):
            i2 = (i + 1) % SEGMENTS
            faces.append((ra[i], rb[i], rb[i2], ra[i2]))
    obj = _new_mesh_object(name, verts, faces, collection)
    for poly in obj.data.polygons:
        poly.use_smooth = True
    return obj


def _extrude_mesh(name, pts2d, depth, collection):
    pts = [(float(p[0]), float(p[1])) for p in pts2d]
    if len(pts) < 3:
        raise ValueError("extrude part %s needs >=3 profile points" % name)
    half = float(depth) / 2.0
    verts = [(x, y, -half) for (x, y) in pts] + [(x, y, half) for (x, y) in pts]
    n = len(pts)
    faces = []
    # caps via tessellation (handles concave polygons)
    tris = tessellate_polygon([[Vector((x, y, 0.0)) for (x, y) in pts]])
    for tri in tris:
        faces.append(tuple(reversed(tuple(tri))))
        faces.append(tuple(n + i for i in tri))
    for i in range(n):
        i2 = (i + 1) % n
        faces.append((i, i2, n + i2, n + i))
    return _new_mesh_object(name, verts, faces, collection)


def build_extrude(name, part, collection):
    profile = part.get("profile") or {}
    pts = profile.get("points") or []
    depth = float(part.get("depth") or 0.05)
    obj = _extrude_mesh(name, pts, depth, collection)
    bevel = obj.modifiers.new("bevel", 'BEVEL')
    bevel.width = min(0.01, depth * 0.1)
    bevel.segments = 2
    bevel.limit_method = 'ANGLE'
    return obj


def build_loft(name, part, collection, subsurf=False):
    profile = part.get("profile") or {}
    sections = profile.get("profiles")
    if not sections:
        # single cross-section lofted between +/- depth/2
        pts = profile.get("points") or []
        depth = float(part.get("depth") or 0.1)
        sections = [{"points": pts, "z": -depth / 2.0},
                    {"points": pts, "z": depth / 2.0}]
    rings = []
    verts = []
    count = max(len(s["points"]) for s in sections)
    for s in sections:
        pts = [(float(p[0]), float(p[1])) for p in s["points"]]
        z = float(s.get("z", 0.0))
        # resample ring to `count` points
        ring = []
        for i in range(count):
            p = pts[int(i * len(pts) / count) % len(pts)]
            ring.append(len(verts))
            verts.append((p[0], p[1], z))
        rings.append(ring)
    faces = []
    for j in range(len(rings) - 1):
        ra, rb = rings[j], rings[j + 1]
        for i in range(count):
            i2 = (i + 1) % count
            faces.append((ra[i], rb[i], rb[i2], ra[i2]))
    for ring, flip in ((rings[0], True), (rings[-1], False)):
        center = len(verts)
        cx = sum(verts[i][0] for i in ring) / count
        cy = sum(verts[i][1] for i in ring) / count
        cz = sum(verts[i][2] for i in ring) / count
        verts.append((cx, cy, cz))
        for i in range(count):
            i2 = (i + 1) % count
            faces.append((center, ring[i2], ring[i]) if flip else (center, ring[i], ring[i2]))
    obj = _new_mesh_object(name, verts, faces, collection)
    for poly in obj.data.polygons:
        poly.use_smooth = True
    if subsurf:
        sub = obj.modifiers.new("subsurf", 'SUBSURF')
        sub.levels = 1
        sub.render_levels = 1
    return obj


def build_sweep(name, part, collection):
    profile = part.get("profile") or {}
    pts = profile.get("points") or []
    if len(pts) < 2:
        raise ValueError("sweep part %s needs >=2 path points" % part.get("id"))
    radius = float(part.get("depth") or 0.02)
    cu = bpy.data.curves.new(name + "_curve", 'CURVE')
    cu.dimensions = '3D'
    cu.resolution_u = 2
    cu.bevel_depth = radius
    cu.bevel_resolution = 3
    cu.use_fill_caps = True
    if len(pts) > 2:
        sp = cu.splines.new('BEZIER')
        sp.bezier_points.add(len(pts) - 1)
        for i, p in enumerate(pts):
            x = float(p[0])
            y = float(p[1])
            z = float(p[2]) if len(p) > 2 else 0.0
            bp = sp.bezier_points[i]
            bp.co = (x, y, z)
            bp.handle_left_type = 'AUTO'
            bp.handle_right_type = 'AUTO'
    else:
        sp = cu.splines.new('POLY')
        sp.points.add(len(pts) - 1)
        for i, p in enumerate(pts):
            x = float(p[0])
            y = float(p[1])
            z = float(p[2]) if len(p) > 2 else 0.0
            sp.points[i].co = (x, y, z, 1.0)
    obj = bpy.data.objects.new(name, cu)
    collection.objects.link(obj)
    return obj


def build_primitive(name, part, collection):
    shape = (part.get("primitive_shape") or "cube").lower()
    scale = (part.get("transform") or {}).get("scale") or [0.2, 0.2, 0.2]
    sx, sy, sz = (float(scale[0]), float(scale[1]), float(scale[2]))
    if shape == "cube":
        bpy.ops.mesh.primitive_cube_add(size=1.0)
        obj = bpy.context.active_object
        obj.scale = (sx, sy, sz)
    elif shape == "cylinder":
        bpy.ops.mesh.primitive_cylinder_add(vertices=SEGMENTS, radius=0.5, depth=1.0)
        obj = bpy.context.active_object
        obj.scale = (sx, sy, sz)
    elif shape == "sphere":
        bpy.ops.mesh.primitive_uv_sphere_add(segments=SEGMENTS, ring_count=24, radius=0.5)
        obj = bpy.context.active_object
        obj.scale = (sx, sy, sz)
        for poly in obj.data.polygons:
            poly.use_smooth = True
    elif shape == "cone":
        bpy.ops.mesh.primitive_cone_add(vertices=SEGMENTS, radius1=0.5, radius2=0.0, depth=1.0)
        obj = bpy.context.active_object
        obj.scale = (sx, sy, sz)
    elif shape == "torus":
        major = sx / 2.0 * 0.75 if sx > 0 else 0.15
        minor = sx / 2.0 * 0.25 if sx > 0 else 0.05
        bpy.ops.mesh.primitive_torus_add(major_radius=major, minor_radius=minor,
                                         major_segments=SEGMENTS, minor_segments=12)
        obj = bpy.context.active_object
        obj.scale = (1.0, sy / sx if sx > 0 else 1.0, 1.0)
        for poly in obj.data.polygons:
            poly.use_smooth = True
    elif shape == "capsule":
        # no capsule op in Blender 5.x: revolve a capsule profile about local Z
        r = sx / 2.0 if sx > 0 else 0.1
        h = max(sz, 2.0 * r + 1e-3)
        prof = []
        steps = 8
        for i in range(steps + 1):
            a = -math.pi / 2.0 + math.pi * i / steps
            prof.append([r * math.cos(a), -h / 2.0 + r + r * math.sin(a)])
        for i in range(steps + 1):
            a = math.pi * i / steps
            prof.append([r * math.cos(a), h / 2.0 - r + r * math.sin(a)])
        fake = {"id": name, "profile": {"points": prof, "closed": False},
                "axis": {"origin": [0, 0, 0], "direction": [0, 0, 1]}}
        obj = build_revolve(name, fake, collection)
    else:
        raise ValueError("unknown primitive_shape %r for part %s" % (shape, part.get("id")))
    # ops-created objects land in the active collection; move to target
    if obj.name not in collection.objects:
        for c in list(obj.users_collection):
            c.objects.unlink(obj)
        collection.objects.link(obj)
    obj.name = name
    if obj.data:
        obj.data.name = name + "_mesh"
    return obj


# --------------------------------------------------------------------------
# hierarchy / collections
# --------------------------------------------------------------------------

def top_level_ancestor(part_id, by_id):
    pid = part_id
    seen = set()
    while by_id.get(pid) and by_id[pid].get("parent") and pid not in seen:
        seen.add(pid)
        pid = by_id[pid]["parent"]
    return pid


def apply_transform(obj, part):
    tr = part.get("transform") or {}
    loc = tr.get("location")
    if loc:
        obj.location = (float(loc[0]), float(loc[1]), float(loc[2]))
    rot = tr.get("rotation_deg")
    if rot:
        obj.rotation_euler = (math.radians(float(rot[0])),
                              math.radians(float(rot[1])),
                              math.radians(float(rot[2])))
    sc = tr.get("scale")
    if sc and part.get("operator") not in ("primitive", "boolean"):
        # primitive builders already consumed transform.scale
        obj.scale = (float(sc[0]), float(sc[1]), float(sc[2]))


def set_custom_props(obj, part):
    obj["recon3d_part_id"] = part.get("id", "")
    obj["recon3d_operator"] = part.get("operator", "")
    params = {k: part.get(k) for k in (
        "primitive_shape", "axis", "depth", "count", "angle_degrees",
        "source_part", "boolean_target", "boolean_operation", "transform")
        if part.get(k) is not None}
    obj["recon3d_params"] = json.dumps(params, sort_keys=True)
    if part.get("profile") is not None:
        obj["recon3d_profile"] = json.dumps(part["profile"], sort_keys=True)


# --------------------------------------------------------------------------
# main build
# --------------------------------------------------------------------------

def main():
    scene = reset_scene()
    parts = PLAN.get("parts") or []
    by_id = {p.get("id"): p for p in parts}

    root = bpy.data.objects.new(PLAN.get("object_id", "recon3d_object"), None)
    scene.collection.objects.link(root)
    root["recon3d_object_id"] = PLAN.get("object_id", "")
    root["recon3d_units"] = PLAN.get("units", "normalized")
    root["recon3d_scene_scale"] = "1 object unit = 1.0 m"
    root["recon3d_generator"] = "recon3d.blender_codegen"
    gscale = (PLAN.get("metadata") or {}).get("global_scale")
    if gscale:
        root.scale = (float(gscale[0]), float(gscale[1]), float(gscale[2]))

    master = bpy.data.collections.new(PLAN.get("object_id", "recon3d"))
    scene.collection.children.link(master)

    collections = {}

    def collection_for(part):
        top = top_level_ancestor(part.get("id"), by_id)
        if top not in collections:
            c = bpy.data.collections.new(str(top))
            master.children.link(c)
            collections[top] = c
        return collections[top]

    built = {}
    skipped = []
    for part in parts:
        pid = part.get("id")
        op = part.get("operator")
        if op in ("displacement", "texture_only"):
            skipped.append(pid)
            root["recon3d_skipped_%s" % pid] = (
                "operator %s: geometry intentionally skipped, detail via texture" % op)
            continue
        coll = collection_for(part)
        try:
            if op == "revolve":
                obj = build_revolve(pid, part, coll)
            elif op == "extrude":
                obj = build_extrude(pid, part, coll)
            elif op == "sweep":
                obj = build_sweep(pid, part, coll)
            elif op == "primitive":
                obj = build_primitive(pid, part, coll)
            elif op == "boolean":
                target_id = part.get("boolean_target")
                target = built.get(target_id)
                if target is None:
                    raise ValueError("boolean target %r not built yet" % target_id)
                profile = (part.get("profile") or {}).get("points") or []
                if len(profile) >= 3:
                    # exact cutter shape from the observed hole outline
                    cutter = _extrude_mesh(
                        pid, profile, float(part.get("depth") or 0.1), coll)
                else:
                    cutter = build_primitive(pid, part, coll)
                mod = target.modifiers.new("boolean_%s" % pid, 'BOOLEAN')
                mod.operation = (part.get("boolean_operation") or "difference").upper()
                if mod.operation not in ("DIFFERENCE", "UNION", "INTERSECT"):
                    mod.operation = "DIFFERENCE"
                try:
                    mod.solver = 'EXACT'
                except Exception:
                    pass
                mod.object = cutter
                cutter.display_type = 'WIRE'
                cutter.hide_render = True
                cutter.hide_set(True)
                cutter["recon3d_is_cutter"] = True
                set_custom_props(cutter, part)
                cutter.parent = built.get(part.get("parent"), root)
                apply_transform(cutter, part)
                built[pid] = cutter
                continue
            elif op == "radial_array":
                src = built.get(part.get("source_part"))
                if src is None:
                    raise ValueError("radial_array source %r not built yet" % part.get("source_part"))
                count = int(part.get("count") or 3)
                total = float(part.get("angle_degrees") or 360.0)
                step = math.radians(total if count <= 1 else (total / count if abs(total - 360.0) < 1e-6 else total / (count - 1)))
                axis = part.get("axis") or {}
                origin = Vector(axis.get("origin", [0.0, 0.0, 0.0]))
                direction = Vector(axis.get("direction", [0.0, 0.0, 1.0])).normalized()
                anchor = bpy.data.objects.new(pid, None)
                coll.objects.link(anchor)
                anchor.location = origin
                anchor["recon3d_part_id"] = pid
                anchor["recon3d_operator"] = "radial_array"
                anchor["recon3d_params"] = json.dumps(
                    {"count": count, "angle_degrees": total,
                     "source_part": part.get("source_part")}, sort_keys=True)
                anchor.parent = built.get(part.get("parent"), root)
                for i in range(count):
                    dup = src.copy()
                    dup.data = src.data           # linked duplicate
                    dup.name = "%s_%02d" % (pid, i)
                    coll.objects.link(dup)
                    rot = Matrix.Translation(origin) @ \\
                        Matrix.Rotation(step * i, 4, direction) @ \\
                        Matrix.Translation(-origin)
                    dup.matrix_world = rot @ src.matrix_world
                    dup.parent = anchor
                    dup.matrix_parent_inverse = anchor.matrix_world.inverted()
                    dup["recon3d_part_id"] = pid
                    dup["recon3d_array_index"] = i
                src["recon3d_array_prototype"] = pid
                built[pid] = anchor
                continue
            elif op == "mirror":
                src = built.get(part.get("source_part"))
                if src is None:
                    raise ValueError("mirror source %r not built yet" % part.get("source_part"))
                mod = src.modifiers.new("mirror_%s" % pid, 'MIRROR')
                direction = ((part.get("axis") or {}).get("direction") or [1.0, 0.0, 0.0])
                dominant = max(range(3), key=lambda i: abs(float(direction[i])))
                mod.use_axis = (dominant == 0, dominant == 1, dominant == 2)
                src["recon3d_mirrored_by"] = pid
                anchor = bpy.data.objects.new(pid, None)
                coll.objects.link(anchor)
                anchor.parent = built.get(part.get("parent"), root)
                anchor["recon3d_part_id"] = pid
                anchor["recon3d_operator"] = "mirror"
                anchor["recon3d_params"] = json.dumps(
                    {"source_part": part.get("source_part"), "axis": direction}, sort_keys=True)
                built[pid] = anchor
                continue
            elif op == "loft":
                obj = build_loft(pid, part, coll, subsurf=False)
            elif op == "freeform":
                obj = build_loft(pid, part, coll, subsurf=True)
            else:
                raise ValueError("unsupported operator %r" % op)
        except Exception as exc:
            errors.append("part %s (%s): %s" % (pid, op, exc))
            continue
        apply_transform(obj, part)
        obj.parent = built.get(part.get("parent"), root)
        set_custom_props(obj, part)
        mat = get_material(part.get("material") or {})
        if hasattr(obj.data, "materials"):
            obj.data.materials.append(mat)
        built[pid] = obj

    bpy.context.view_layer.objects.active = root
    root.select_set(True)

    # ---- exports ------------------------------------------------------
    bpy.ops.wm.save_as_mainfile(filepath=BLEND_PATH)
    bpy.ops.export_scene.gltf(
        filepath=GLB_PATH,
        export_format='GLB',
        export_apply=False,          # keep modifiers un-applied
        export_yup=True,
        export_extras=True,          # carry custom properties
        export_cameras=False,
        export_lights=False,
    )

    # ---- manifest ------------------------------------------------------
    objects = []
    for obj in bpy.data.objects:
        info = {
            "name": obj.name,
            "type": obj.type,
            "collection": obj.users_collection[0].name if obj.users_collection else "",
            "parent": obj.parent.name if obj.parent else None,
            "part_id": obj.get("recon3d_part_id"),
            "modifiers": [m.type for m in getattr(obj, "modifiers", [])],
            "materials": [ms.material.name for ms in getattr(obj, "material_slots", [])
                          if ms.material],
            "has_uv": bool(getattr(obj.data, "uv_layers", [])) if obj.type == 'MESH' else False,
            "vertex_count": len(obj.data.vertices) if obj.type == 'MESH' else 0,
            "face_count": len(obj.data.polygons) if obj.type == 'MESH' else 0,
            "is_manifold": None,
            "pivot": [round(v, 6) for v in obj.matrix_world.translation],
        }
        objects.append(info)
    return {
        "blend_path": BLEND_PATH,
        "glb_path": GLB_PATH,
        "objects": objects,
        "collections": sorted(c.name for c in bpy.data.collections),
        "blender_version": bpy.app.version_string,
        "skipped_parts": skipped,
    }


manifest = {
    "blend_path": BLEND_PATH,
    "glb_path": GLB_PATH,
    "objects": [],
    "collections": [],
    "blender_version": "",
    "success": False,
    "errors": [],
}
try:
    built_manifest = main()
    manifest.update(built_manifest)
    manifest["errors"] = errors
    manifest["success"] = len(errors) == 0
except Exception:
    import traceback
    manifest["errors"] = errors + [traceback.format_exc()]
    manifest["success"] = False

with open(MANIFEST_PATH, "w") as fh:
    json.dump(manifest, fh, indent=2, sort_keys=True)
print("RECON3D_MANIFEST_WRITTEN success=%s" % manifest["success"])
'''


def _ordered_plan_data(plan: ConstructionPlan) -> dict:
    """Return plan data in deterministic Blender build-dependency order.

    Parent objects, boolean targets, and array/mirror prototypes precede the
    parts that consume them. Validation rejects cycles; the stable fallback at
    the end keeps script generation deterministic even for an invalid plan.
    """
    data = plan.model_dump(mode="json")
    pending = list(data.get("parts") or [])
    ids = {p.get("id") for p in pending}
    ordered = []
    built = set()
    while pending:
        progressed = False
        for part in list(pending):
            deps = [part.get("parent"), part.get("boolean_target"),
                    part.get("source_part")]
            deps = {d for d in deps if d in ids and d != part.get("id")}
            if deps <= built:
                ordered.append(part)
                built.add(part.get("id"))
                pending.remove(part)
                progressed = True
        if not progressed:
            ordered.extend(pending)
            break
    data["parts"] = ordered
    return data


def _plan_to_json(plan: ConstructionPlan) -> str:
    """Serialise the plan deterministically (sorted keys, enums to values)."""
    return json.dumps(_ordered_plan_data(plan), sort_keys=True)


def generate_blender_script(plan: ConstructionPlan, out_dir: str,
                            cfg: PipelineConfig) -> str:
    """Write <out_dir>/build_model.py for the plan and return its path.

    Pure function of the plan: identical plans produce identical scripts.
    """
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    plan_json = _plan_to_json(plan)
    # embed as a JSON string literal (double-encoded, quote-safe)
    script = _SCRIPT_TEMPLATE.replace("__PLAN_JSON__", json.dumps(plan_json))
    engine = getattr(cfg.blender, "render_engine", "BLENDER_EEVEE") or "BLENDER_EEVEE"
    script = script.replace("__RENDER_ENGINE__", json.dumps(engine))
    path = out / "build_model.py"
    path.write_text(script)
    return str(path)
