"""Render-based joint multiview pose and depth refinement.

The primary-view construction plan fixes observed XY geometry.  Secondary
silhouettes constrain the otherwise weakly observed Z extent and relative
object yaw.  A single sandboxed Blender invocation renders a bounded grid of
depth scales and yaw hypotheses; the host scores every silhouette, selects one
shared depth scale across views, and retains it only when mean agreement
improves.  This makes Phase 6 alter inferred 3D geometry without overwriting
primary observed curves.
"""
from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Dict, List, Tuple

import cv2
import numpy as np

from . import runner, validation
from .config import PipelineConfig
from .schemas import (ConstructionPlan, CropMetadata, EvidenceSource,
                      EvidencedValue, MultiViewResult, SegmentationResult)


_SCRIPT = '''\
# Auto-generated by recon3d.multiview_refinement. Do not edit by hand.
import json
import math
import os
import sys

import bpy

ARGV = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else sys.argv[1:]
PROJECT_DIR, BLEND_PATH, _GLB_PATH, MANIFEST_PATH = ARGV[:4]
PARAMS = json.loads(__PARAMS_JSON__)

manifest = {"blend_path": BLEND_PATH, "glb_path": None, "objects": [],
            "collections": [], "blender_version": bpy.app.version_string,
            "success": False, "errors": []}

try:
    bpy.ops.wm.open_mainfile(filepath=BLEND_PATH)
    scene = bpy.context.scene
    try:
        scene.render.engine = PARAMS["render_engine"]
    except Exception:
        scene.render.engine = "BLENDER_EEVEE"
    resolution = int(PARAMS["resolution"])
    scene.render.resolution_x = resolution
    scene.render.resolution_y = resolution
    scene.render.resolution_percentage = 100
    scene.render.image_settings.file_format = "PNG"
    scene.render.image_settings.color_mode = "BW"
    scene.render.film_transparent = False
    scene.render.resolution_percentage = 100
    scene.render.image_settings.color_depth = "8"
    scene.view_settings.view_transform = "Standard"

    root = next((o for o in bpy.data.objects if o.get("recon3d_object_id")), None)
    if root is None:
        raise RuntimeError("recon3d root object not found")
    base_scale = root.scale.copy()
    base_rotation = root.rotation_euler.copy()

    world = bpy.data.worlds.new("recon3d_multiview_world")
    world.use_nodes = True
    bg = world.node_tree.nodes.get("Background")
    bg.inputs["Color"].default_value = (0.0, 0.0, 0.0, 1.0)
    bg.inputs["Strength"].default_value = 0.0
    scene.world = world

    material = bpy.data.materials.new("recon3d_multiview_mask")
    material.use_nodes = True
    nodes = material.node_tree.nodes
    nodes.clear()
    out = nodes.new("ShaderNodeOutputMaterial")
    emission = nodes.new("ShaderNodeEmission")
    emission.inputs["Color"].default_value = (1.0, 1.0, 1.0, 1.0)
    emission.inputs["Strength"].default_value = 1.0
    material.node_tree.links.new(emission.outputs["Emission"], out.inputs["Surface"])
    scene.view_layers[0].material_override = material

    camera_data = bpy.data.cameras.new("recon3d_multiview_camera")
    camera = bpy.data.objects.new("recon3d_multiview_camera", camera_data)
    scene.collection.objects.link(camera)
    scene.camera = camera
    camera_data.sensor_width = 36.0
    camera_data.sensor_fit = "HORIZONTAL"

    written = []
    for candidate in PARAMS["candidates"]:
        root.scale = base_scale.copy()
        root.scale.z = base_scale.z * float(candidate["depth_scale"])
        root.rotation_euler = base_rotation.copy()
        rotation = candidate["object_rotation_deg"]
        root.rotation_euler.x += math.radians(float(rotation[0]))
        root.rotation_euler.y += math.radians(float(rotation[1]))
        root.rotation_euler.z += math.radians(float(rotation[2]))

        focal = float(candidate["focal_px"])
        camera_data.lens = focal / resolution * camera_data.sensor_width
        camera_data.type = "PERSP"
        camera.location = tuple(float(v) for v in candidate["translation"])
        camera.rotation_euler = (0.0, 0.0, 0.0)

        path = os.path.join(PARAMS["output_dir"], candidate["filename"])
        scene.render.filepath = path
        bpy.ops.render.render(write_still=True)
        written.append(path)

    root.scale = base_scale
    root.rotation_euler = base_rotation
    manifest["success"] = True
    manifest["collections"] = [c.name for c in bpy.data.collections]
    manifest["written"] = written
except Exception as exc:
    import traceback
    manifest["errors"] = [str(exc), traceback.format_exc()]

with open(MANIFEST_PATH, "w") as fh:
    json.dump(manifest, fh, indent=2, sort_keys=True)
'''


def _reference_mask(observation, resolution: int) -> np.ndarray | None:
    if not observation.mask_path or not observation.crop_metadata_path:
        return None
    mask = cv2.imread(observation.mask_path, cv2.IMREAD_GRAYSCALE)
    if mask is None:
        return None
    try:
        crop_meta = CropMetadata.model_validate_json(
            Path(observation.crop_metadata_path).read_text())
    except Exception:
        return None
    remapped = validation.remap_to_crop(mask, crop_meta)
    remapped = validation._binarize(remapped)
    return cv2.resize(remapped, (resolution, resolution),
                      interpolation=cv2.INTER_NEAREST)


def _primary_reference_mask(seg: SegmentationResult | None,
                            crop_meta: CropMetadata | None,
                            resolution: int) -> np.ndarray | None:
    if seg is None or crop_meta is None:
        return None
    mask = cv2.imread(seg.mask_path, cv2.IMREAD_GRAYSCALE)
    if mask is None:
        return None
    remapped = validation._binarize(validation.remap_to_crop(mask, crop_meta))
    return cv2.resize(remapped, (resolution, resolution),
                      interpolation=cv2.INTER_NEAREST)


def _base_object_rotation(plan: ConstructionPlan) -> List[float]:
    if plan.camera is None:
        return [0.0, 0.0, 0.0]
    value = plan.camera.object_rotation_euler_deg.value
    if isinstance(value, list) and len(value) == 3:
        return [float(v) for v in value]
    return [0.0, 0.0, 0.0]


def _candidate_grid(plan: ConstructionPlan, result: MultiViewResult,
                    cfg: PipelineConfig,
                    primary_seg: SegmentationResult | None = None,
                    primary_crop_meta: CropMetadata | None = None,
                    ) -> Tuple[List[Dict], Dict[str, np.ndarray]]:
    resolution = cfg.multiview.joint_render_resolution
    focal = cfg.camera.default_focal_px * resolution / cfg.crop.canvas_size
    rotations = _base_object_rotation(plan)
    yaws = list(range(-180, 180, cfg.multiview.yaw_step_deg))
    scales = sorted(set(float(v) for v in
                        cfg.multiview.depth_scale_candidates if v > 0.0))
    if 1.0 not in scales:
        scales.append(1.0)
        scales.sort()

    references: Dict[str, np.ndarray] = {}
    candidates: List[Dict] = []
    primary_ref = _primary_reference_mask(
        primary_seg, primary_crop_meta, resolution)
    if primary_ref is not None and int(primary_ref.sum()) >= 10:
        references["view_000"] = primary_ref
        translation, _ = validation._framing(primary_ref, focal)
        for scale_index, scale in enumerate(scales):
            candidates.append({
                "view_id": "view_000",
                "depth_scale": scale,
                "yaw_deg": 0.0,
                "filename": "view_000_s%02d_y+000.png" % scale_index,
                "focal_px": focal,
                "translation": list(translation),
                "object_rotation_deg": rotations,
            })
    for observation in result.observations:
        if observation.status != "success":
            continue
        ref = _reference_mask(observation, resolution)
        if ref is None or int(ref.sum()) < 10:
            continue
        references[observation.view_id] = ref
        translation, _ = validation._framing(ref, focal)
        pose = result.relative_camera_poses.get(observation.view_id)
        pose_value = pose.value if pose is not None else None
        if (pose is not None and pose.source == EvidenceSource.USER_SUPPLIED
                and isinstance(pose_value, list) and len(pose_value) == 3):
            # Moving the camera +azimuth is equivalent to rotating the object
            # by -azimuth in the fixed reconstruction camera.
            view_yaws = [-float(pose_value[1])]
        else:
            view_yaws = yaws
        for scale_index, scale in enumerate(scales):
            for yaw in view_yaws:
                filename = "%s_s%02d_y%+04d.png" % (
                    observation.view_id, scale_index, yaw)
                candidates.append({
                    "view_id": observation.view_id,
                    "depth_scale": scale,
                    "yaw_deg": float(yaw),
                    "filename": filename,
                    "focal_px": focal,
                    "translation": list(translation),
                    "object_rotation_deg": [rotations[0],
                                            rotations[1] + float(yaw),
                                            rotations[2]],
                })
    return candidates, references


def _write_script(project: Path, candidates: List[Dict],
                  cfg: PipelineConfig) -> Path:
    output_dir = project / "validation" / "multiview_candidates"
    output_dir.mkdir(parents=True, exist_ok=True)
    params = {
        "render_engine": cfg.blender.render_engine or "BLENDER_EEVEE",
        "resolution": cfg.multiview.joint_render_resolution,
        "output_dir": str(output_dir),
        "candidates": candidates,
    }
    text = _SCRIPT.replace("__PARAMS_JSON__",
                           json.dumps(json.dumps(params, sort_keys=True)))
    path = project / "blender" / "render_multiview_candidates.py"
    path.write_text(text)
    return path


def _score_candidates(project: Path, candidates: List[Dict],
                      references: Dict[str, np.ndarray]
                      ) -> Tuple[Dict[float, Dict[str, Dict]], Dict]:
    output_dir = project / "validation" / "multiview_candidates"
    by_scale: Dict[float, Dict[str, Dict]] = {}
    all_scores = []
    for candidate in candidates:
        image = cv2.imread(str(output_dir / candidate["filename"]),
                           cv2.IMREAD_GRAYSCALE)
        if image is None:
            continue
        rendered = validation._binarize(image)
        reference = references[candidate["view_id"]]
        iou = validation._iou(reference, rendered)
        scale = float(candidate["depth_scale"])
        per_view = by_scale.setdefault(scale, {})
        previous = per_view.get(candidate["view_id"])
        if previous is None or iou > previous["silhouette_iou"]:
            per_view[candidate["view_id"]] = {
                "yaw_deg": candidate["yaw_deg"],
                "silhouette_iou": iou,
                "render_path": str(output_dir / candidate["filename"]),
            }
        all_scores.append(iou)
    diagnostics = {
        "candidate_count": len(candidates),
        "rendered_candidate_count": len(all_scores),
        "candidate_iou_mean": float(np.mean(all_scores)) if all_scores else None,
    }
    return by_scale, diagnostics


def refine_multiview_geometry(
    plan: ConstructionPlan,
    result: MultiViewResult,
    project_dir: str,
    cfg: PipelineConfig,
    primary_seg: SegmentationResult | None = None,
    primary_crop_meta: CropMetadata | None = None,
) -> Tuple[ConstructionPlan, MultiViewResult, bool]:
    """Jointly fit relative yaw and one shared inferred depth scale.

    Returns the potentially updated plan/result and whether Blender geometry
    must be rebuilt.
    """
    if (not result.enabled or not cfg.multiview.joint_refinement_enabled
            or not any(o.status == "success" for o in result.observations)):
        return plan, result, False

    project = Path(project_dir).resolve()
    candidates, references = _candidate_grid(
        plan, result, cfg, primary_seg, primary_crop_meta)
    if not candidates or not (set(references) - {"view_000"}):
        result.warnings.append(
            "joint multiview refinement skipped: no usable secondary masks")
        return plan, result, False

    script = _write_script(project, candidates, cfg)
    manifest = runner.run_blender(str(script), str(project), cfg)
    if not manifest.success:
        result.warnings.append(
            "joint multiview refinement render failed: %s"
            % "; ".join(manifest.errors))
        return plan, result, False

    by_scale, diagnostics = _score_candidates(project, candidates, references)
    expected_views = set(references)
    complete = {
        scale: views for scale, views in by_scale.items()
        if set(views) == expected_views
    }
    if not complete:
        result.warnings.append(
            "joint multiview refinement produced no complete scale candidate")
        return plan, result, False

    secondary_ids = expected_views - {"view_000"}
    means = {
        scale: float(np.mean([views[view_id]["silhouette_iou"]
                              for view_id in secondary_ids]))
        for scale, views in complete.items()
    }
    baseline_scale = min(means, key=lambda value: abs(value - 1.0))
    baseline_primary = complete[baseline_scale].get(
        "view_000", {}).get("silhouette_iou")
    eligible = dict(complete)
    if baseline_primary is not None:
        eligible = {
            scale: views for scale, views in complete.items()
            if views["view_000"]["silhouette_iou"]
            >= baseline_primary - cfg.multiview.max_primary_iou_drop
        }
    unconstrained_best_scale = max(
        complete, key=lambda value: (means[value], -abs(value - 1.0)))
    best_scale = max(eligible, key=lambda value: (means[value],
                                                   -abs(value - 1.0)))
    best_mean = means[best_scale]
    baseline_mean = means[baseline_scale]
    gain = best_mean - baseline_mean
    retained = (abs(best_scale - 1.0) > 1e-9
                and gain >= cfg.multiview.min_joint_iou_gain)

    refined = plan.model_copy(deep=True)
    if retained:
        metadata = dict(refined.metadata or {})
        global_scale = list(metadata.get("global_scale") or [1.0, 1.0, 1.0])
        while len(global_scale) < 3:
            global_scale.append(1.0)
        global_scale[2] = float(global_scale[2]) * best_scale
        metadata["global_scale"] = [round(float(v), 6) for v in global_scale]
        metadata["multiview_depth_scale"] = {
            "value": best_scale,
            "source": EvidenceSource.FITTED_FROM_OBSERVATION.value,
            "confidence": min(0.9, 0.45 + max(0.0, gain)),
        }
        refined.metadata = metadata

    selected_scale = best_scale if retained else baseline_scale
    selected_views = complete[selected_scale]
    for view_id, entry in selected_views.items():
        if view_id == "view_000":
            continue
        existing_pose = result.relative_camera_poses.get(view_id)
        if (existing_pose is None
                or existing_pose.source != EvidenceSource.USER_SUPPLIED):
            result.relative_camera_poses[view_id] = EvidencedValue(
                value=[0.0, -float(entry["yaw_deg"]), 0.0], unit="deg",
                source=EvidenceSource.FITTED_FROM_OBSERVATION,
                confidence=min(0.9, 0.45 + entry["silhouette_iou"] * 0.45),
                note=("render-validated relative camera yaw; secondary "
                      "silhouette evidence"),
            )

    result.joint_optimization = {
        "method": "bounded joint secondary-silhouette coordinate search",
        "optimized_parameters": ["relative_camera_yaw", "shared_depth_scale"],
        "views_used": len(secondary_ids),
        "candidate_count": diagnostics["candidate_count"],
        "rendered_candidate_count": diagnostics["rendered_candidate_count"],
        "baseline_depth_scale": baseline_scale,
        "baseline_mean_silhouette_iou": baseline_mean,
        "baseline_primary_silhouette_iou": baseline_primary,
        "selected_depth_scale": selected_scale,
        "selected_mean_silhouette_iou": means[selected_scale],
        "selected_primary_silhouette_iou": selected_views.get(
            "view_000", {}).get("silhouette_iou"),
        "best_depth_scale": best_scale,
        "best_mean_silhouette_iou": best_mean,
        "unconstrained_best_depth_scale": unconstrained_best_scale,
        "unconstrained_best_mean_silhouette_iou": means[
            unconstrained_best_scale],
        "mean_iou_gain": gain if retained else 0.0,
        "depth_scale_retained": retained,
        "per_view": {key: value for key, value in selected_views.items()
                     if key != "view_000"},
        "primary_observed_geometry_overwritten": False,
    }
    return refined, result, retained
