"""Stage 17: render-based validation.

Generates a second Blender script (blender/render_validation.py) that opens
scene.blend, places a camera from plan.camera (framing matched to the
reference crop), and renders silhouette / clay / normal / depth / part-id /
full-shaded passes plus turntable frames. The host then compares the renders
against the reference mask and writes overlays, metrics.json and
turntable.mp4 into validation/.
"""
from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Optional, Tuple

import cv2
import numpy as np

from . import runner
from .config import PipelineConfig
from .schemas import (BlenderManifest, ConstructionPlan, CropMetadata,
                      SchemaIO, SegmentationResult, ValidationMetrics,
                      ValidationResult)


# ---------------------------------------------------------------------------
# reference remapping (original image space -> crop canvas)
# ---------------------------------------------------------------------------

def _crop_warp_matrix(crop_meta: CropMetadata) -> np.ndarray:
    s = crop_meta.scale
    ox, oy = crop_meta.offset
    return np.array([[s, 0.0, -ox * s], [0.0, s, -oy * s]], dtype=np.float64)


def remap_to_crop(img: np.ndarray, crop_meta: CropMetadata,
                  interpolation: int = cv2.INTER_NEAREST) -> np.ndarray:
    m = _crop_warp_matrix(crop_meta)
    w, h = crop_meta.output_size
    return cv2.warpAffine(img, m, (w, h), flags=interpolation,
                          borderMode=cv2.BORDER_CONSTANT, borderValue=0)


# ---------------------------------------------------------------------------
# render script generation
# ---------------------------------------------------------------------------

_RENDER_TEMPLATE = '''\
# Auto-generated by recon3d.validation. Do not edit by hand.
import json
import math
import os
import sys

import bpy
from mathutils import Vector

ARGV = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else sys.argv[1:]
PROJECT_DIR = os.path.abspath(ARGV[0])
BLEND_PATH = ARGV[1]          # input scene.blend from stage 15
MANIFEST_PATH = ARGV[3]

PARAMS = json.loads(__PARAMS_JSON__)

errors = []


def _point_at(obj, target):
    direction = Vector(target) - obj.location
    obj.rotation_euler = direction.to_track_quat('-Z', 'Y').to_euler()


def _emission_material(name, color, strength=1.0):
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    nt = mat.node_tree
    nt.nodes.clear()
    out = nt.nodes.new("ShaderNodeOutputMaterial")
    em = nt.nodes.new("ShaderNodeEmission")
    em.inputs["Color"].default_value = (color[0], color[1], color[2], 1.0)
    em.inputs["Strength"].default_value = strength
    nt.links.new(em.outputs["Emission"], out.inputs["Surface"])
    return mat


def _depth_material(near, far):
    mat = bpy.data.materials.new("recon3d_depth")
    mat.use_nodes = True
    nt = mat.node_tree
    nt.nodes.clear()
    out = nt.nodes.new("ShaderNodeOutputMaterial")
    em = nt.nodes.new("ShaderNodeEmission")
    cam = nt.nodes.new("ShaderNodeCameraData")
    sub = nt.nodes.new("ShaderNodeMath"); sub.operation = 'SUBTRACT'
    sub.inputs[1].default_value = near
    div = nt.nodes.new("ShaderNodeMath"); div.operation = 'DIVIDE'
    div.inputs[1].default_value = max(far - near, 1e-6)
    inv = nt.nodes.new("ShaderNodeMath"); inv.operation = 'SUBTRACT'
    inv.inputs[0].default_value = 1.0
    mn = nt.nodes.new("ShaderNodeMath"); mn.operation = 'MINIMUM'
    mn.inputs[1].default_value = 1.0
    mx = nt.nodes.new("ShaderNodeMath"); mx.operation = 'MAXIMUM'
    mx.inputs[1].default_value = 0.0
    nt.links.new(cam.outputs["View Z Depth"], sub.inputs[0])
    nt.links.new(sub.outputs[0], div.inputs[0])
    nt.links.new(div.outputs[0], inv.inputs[1])
    nt.links.new(inv.outputs[0], mn.inputs[0])
    nt.links.new(mn.outputs[0], mx.inputs[0])
    nt.links.new(mx.outputs[0], em.inputs["Color"])
    nt.links.new(em.outputs["Emission"], out.inputs["Surface"])
    return mat


def _normal_material():
    mat = bpy.data.materials.new("recon3d_normal")
    mat.use_nodes = True
    nt = mat.node_tree
    nt.nodes.clear()
    out = nt.nodes.new("ShaderNodeOutputMaterial")
    em = nt.nodes.new("ShaderNodeEmission")
    geo = nt.nodes.new("ShaderNodeNewGeometry")
    mul = nt.nodes.new("ShaderNodeVectorMath"); mul.operation = 'MULTIPLY'
    mul.inputs[1].default_value = (0.5, 0.5, 0.5)
    add = nt.nodes.new("ShaderNodeVectorMath"); add.operation = 'ADD'
    add.inputs[1].default_value = (0.5, 0.5, 0.5)
    nt.links.new(geo.outputs["Normal"], mul.inputs[0])
    nt.links.new(mul.outputs[0], add.inputs[0])
    nt.links.new(add.outputs[0], em.inputs["Color"])
    nt.links.new(em.outputs["Emission"], out.inputs["Surface"])
    return mat


def _clay_material():
    mat = bpy.data.materials.new("recon3d_clay")
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes.get("Principled BSDF")
    bsdf.inputs["Base Color"].default_value = (0.5, 0.5, 0.5, 1.0)
    bsdf.inputs["Roughness"].default_value = 0.9
    bsdf.inputs["Metallic"].default_value = 0.0
    return mat


def main():
    p = PARAMS
    bpy.ops.wm.open_mainfile(filepath=BLEND_PATH)
    scene = bpy.context.scene
    try:
        scene.render.engine = p["render_engine"]
    except Exception:
        scene.render.engine = 'BLENDER_EEVEE'
    res = int(p["resolution"])
    scene.render.resolution_x = res
    scene.render.resolution_y = res
    scene.render.image_settings.file_format = 'PNG'
    scene.render.film_transparent = False
    scene.view_settings.view_transform = 'Standard'
    try:
        scene.view_settings.look = 'None'
    except Exception:
        pass

    out_dir = p["output_dir"]
    os.makedirs(out_dir, exist_ok=True)

    root = None
    for obj in bpy.data.objects:
        if obj.get("recon3d_object_id"):
            root = obj
            break

    # ---- camera --------------------------------------------------------
    cam_data = bpy.data.cameras.new("recon3d_validation_cam")
    cam = bpy.data.objects.new("recon3d_validation_cam", cam_data)
    scene.collection.objects.link(cam)
    scene.camera = cam
    cam_data.sensor_width = 36.0
    cam_data.sensor_fit = 'HORIZONTAL'
    focal_px = float(p["focal_px"])
    cam_data.lens = focal_px / res * cam_data.sensor_width
    tx, ty, tz = p["camera_translation"]
    cam.location = (tx, ty, tz)
    rot = p.get("camera_rotation_deg") or [0.0, 0.0, 0.0]
    cam.rotation_euler = (math.radians(rot[0]), math.radians(rot[1]),
                          math.radians(rot[2]))
    if p.get("projection") == "orthographic":
        cam_data.type = 'ORTHO'
        cam_data.ortho_scale = float(p["ortho_scale"])
    if root is not None:
        orot = p.get("object_rotation_deg") or [0.0, 0.0, 0.0]
        root.rotation_euler = (math.radians(orot[0]), math.radians(orot[1]),
                               math.radians(orot[2]))

    # ---- world + lights -------------------------------------------------
    world = bpy.data.worlds.new("recon3d_world")
    world.use_nodes = True
    bg = world.node_tree.nodes.get("Background")
    scene.world = world

    lights = []
    for name, loc, energy, size in (
            ("key", (2.5, 3.0, 2.0), 700.0, 1.5),
            ("fill", (-3.0, 0.5, 2.5), 300.0, 2.0),
            ("rim", (-0.5, 2.5, -3.0), 500.0, 1.0)):
        ld = bpy.data.lights.new("recon3d_%s" % name, 'AREA')
        ld.energy = energy
        ld.shape = 'DISK'
        ld.size = size
        lo = bpy.data.objects.new("recon3d_%s" % name, ld)
        scene.collection.objects.link(lo)
        lo.location = loc
        _point_at(lo, (0.0, 0.0, 0.0))
        lights.append(lo)

    layer = scene.view_layers[0]
    written = []

    def render_pass(fname, color_depth='8'):
        scene.render.image_settings.color_depth = color_depth
        scene.render.filepath = os.path.join(out_dir, fname)
        bpy.ops.render.render(write_still=True)
        written.append(scene.render.filepath)

    # silhouette: white emission override on black world
    bg.inputs["Color"].default_value = (0.0, 0.0, 0.0, 1.0)
    bg.inputs["Strength"].default_value = 0.0
    layer.material_override = _emission_material("recon3d_white", (1, 1, 1))
    render_pass("render_silhouette.png")

    # clay: uniform gray under the lights, black world (background stays 0
    # so the host can threshold the clay silhouette cleanly)
    layer.material_override = _clay_material()
    render_pass("render_clay.png")

    # normal (world space, black world)
    bg.inputs["Color"].default_value = (0.0, 0.0, 0.0, 1.0)
    layer.material_override = _normal_material()
    render_pass("render_normal.png")

    # depth: near bright -> far dark, 16-bit
    d = float(p["camera_translation"][2])
    layer.material_override = _depth_material(d - 1.5, d + 1.5)
    render_pass("render_depth.png", color_depth='16')

    # full shaded: plan materials, neutral world
    layer.material_override = None
    bg.inputs["Color"].default_value = (0.05, 0.05, 0.05, 1.0)
    render_pass("render_shaded.png")

    # Preserve original slots once so both categorical passes can safely
    # replace and then restore materials, including meshes without slots.
    bg.inputs["Color"].default_value = (0.0, 0.0, 0.0, 1.0)
    saved_mats = {
        obj.name: [slot.material for slot in obj.material_slots]
        for obj in bpy.data.objects if obj.type == 'MESH'
    }

    def restore_materials():
        for obj_name, mats in saved_mats.items():
            obj = bpy.data.objects.get(obj_name)
            if obj is None or obj.type != 'MESH':
                continue
            obj.data.materials.clear()
            for mat in mats:
                if mat is not None:
                    obj.data.materials.append(mat)

    # part-id: per top-level part emission colour
    groups = {}
    for obj in bpy.data.objects:
        if obj.type != 'MESH':
            continue
        anc = obj
        while anc.parent is not None and anc.parent is not root:
            anc = anc.parent
        gid = anc.name if anc is not root else anc.name
        groups.setdefault(gid, []).append(obj)
    import colorsys
    gids = sorted(groups.keys())
    for gi, gid in enumerate(gids):
        hue = (gi * 0.61803398875) % 1.0   # golden-ratio spread, deterministic
        col = colorsys.hsv_to_rgb(hue, 0.75, 1.0)
        mat = _emission_material("recon3d_pid_%02d" % gi, col)
        for obj in groups[gid]:
            if obj.material_slots:
                for s in obj.material_slots:
                    s.material = mat
            else:
                obj.data.materials.append(mat)
    render_pass("render_partid.png")
    restore_materials()

    # material-id: one deterministic emission colour per original material
    material_groups = {}
    for obj in bpy.data.objects:
        if obj.type != 'MESH':
            continue
        signature = tuple(sorted(
            slot.material.name for slot in obj.material_slots
            if slot.material is not None)) or ("unassigned",)
        material_groups.setdefault(signature, []).append(obj)
    for mi, signature in enumerate(sorted(material_groups)):
        hue = (mi * 0.61803398875) % 1.0
        col = colorsys.hsv_to_rgb(hue, 0.75, 1.0)
        mat = _emission_material("recon3d_mid_%02d" % mi, col)
        for obj in material_groups[signature]:
            if obj.material_slots:
                for slot in obj.material_slots:
                    slot.material = mat
            else:
                obj.data.materials.append(mat)
    render_pass("render_materialid.png")
    restore_materials()

    # turntable: rotate root about the object up-axis (Blender Y here)
    tt_dir = os.path.join(out_dir, "turntable_frames")
    os.makedirs(tt_dir, exist_ok=True)
    bg.inputs["Color"].default_value = (0.05, 0.05, 0.05, 1.0)
    n_frames = int(p.get("turntable_frames", 24))
    tt_res = int(p.get("turntable_resolution", res))
    scene.render.resolution_x = tt_res
    scene.render.resolution_y = tt_res
    base_rot = root.rotation_euler.copy() if root is not None else None
    for i in range(n_frames):
        if root is not None:
            root.rotation_euler = base_rot.copy()
            root.rotation_euler.y = base_rot.y + 2.0 * math.pi * i / n_frames
        scene.render.filepath = os.path.join(tt_dir, "tt_%03d.png" % i)
        bpy.ops.render.render(write_still=True)
        written.append(scene.render.filepath)
    if root is not None:
        root.rotation_euler = base_rot

    return {"written": written, "objects": len(bpy.data.objects)}


manifest = {"blend_path": BLEND_PATH, "glb_path": None, "objects": [],
            "collections": [], "blender_version": "", "success": False,
            "errors": []}
try:
    info = main()
    manifest["success"] = True
    manifest["blender_version"] = bpy.app.version_string
    manifest["rendered_files"] = info["written"]
except Exception:
    import traceback
    manifest["errors"] = errors + [traceback.format_exc()]
    manifest["success"] = False

with open(MANIFEST_PATH, "w") as fh:
    json.dump(manifest, fh, indent=2, sort_keys=True)
print("RECON3D_RENDER_MANIFEST_WRITTEN success=%s" % manifest["success"])
'''


def _evidenced(ev, default):
    v = getattr(ev, "value", None)
    if v is None:
        return default
    return v


def _framing(ref_mask: np.ndarray, focal_px: float
             ) -> Tuple[Tuple[float, float, float], float]:
    """Camera translation (x, y, z) + ortho scale so the object fills the
    frame exactly like the reference mask does on the crop canvas."""
    h, w = ref_mask.shape
    ys, xs = np.nonzero(ref_mask)
    if len(xs) == 0:
        return (0.0, 0.0, 2.0), 2.0
    x0, x1 = xs.min(), xs.max() + 1
    y0, y1 = ys.min(), ys.max() + 1
    bw = max(x1 - x0, 1)
    cx = (x0 + x1) / 2.0 / w
    cy = (y0 + y1) / 2.0 / h
    fw = bw / w
    dist = focal_px / bw          # object width 1.0 projects to bw pixels
    view_w = 1.0 / fw             # world width visible at the object plane
    ox = -(cx - 0.5) * view_w
    oy = (cy - 0.5) * view_w      # image y down -> world y up
    return (ox, oy, dist), view_w


def generate_render_script(plan: ConstructionPlan, ref_mask: np.ndarray,
                           project_dir: str, cfg: PipelineConfig) -> str:
    """Write blender/render_validation.py and return its path."""
    cam = plan.camera
    focal_px = cfg.camera.default_focal_px
    projection = "perspective"
    rot = [0.0, 0.0, 0.0]
    orot = [0.0, 0.0, 0.0]
    translation = None
    if cam is not None:
        focal_px = float(_evidenced(cam.focal_length_px, focal_px))
        projection = cam.projection.value
        rot = [float(v) for v in _evidenced(cam.rotation_euler_deg, rot)]
        orot = [float(v) for v in _evidenced(cam.object_rotation_euler_deg, orot)]
        translation = _evidenced(cam.translation, None)
    framed_t, view_w = _framing(ref_mask, focal_px)
    if translation is None:
        translation = list(framed_t)
    else:
        translation = [float(v) for v in translation]
    camera_offset = (plan.metadata or {}).get("validation_camera_offset")
    if camera_offset and len(camera_offset) >= 2:
        translation[0] += float(camera_offset[0])
        translation[1] += float(camera_offset[1])
    params = {
        "render_engine": cfg.blender.render_engine or "BLENDER_EEVEE",
        "resolution": int(ref_mask.shape[0]),
        "output_dir": str(Path(project_dir).resolve() / "validation"),
        "focal_px": focal_px,
        "projection": projection,
        "ortho_scale": view_w,
        "camera_translation": translation,
        "camera_rotation_deg": rot,
        "object_rotation_deg": orot,
        "turntable_frames": 24,
        "turntable_resolution": min(512, int(ref_mask.shape[0])),
        "seed": cfg.seed,
    }
    script = _RENDER_TEMPLATE.replace(
        "__PARAMS_JSON__", json.dumps(json.dumps(params, sort_keys=True)))
    out = Path(project_dir) / "blender"
    out.mkdir(parents=True, exist_ok=True)
    path = out / "render_validation.py"
    path.write_text(script)
    return str(path)


# ---------------------------------------------------------------------------
# metrics helpers
# ---------------------------------------------------------------------------

def _binarize(img: np.ndarray, thresh: int = 127) -> np.ndarray:
    if img.ndim == 3:
        img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    return (img > thresh).astype(np.uint8)


def _iou(a: np.ndarray, b: np.ndarray) -> float:
    inter = float(np.logical_and(a, b).sum())
    union = float(np.logical_or(a, b).sum())
    return inter / union if union > 0 else 0.0


def _chamfer(a: np.ndarray, b: np.ndarray) -> float:
    """Symmetric chamfer distance between mask contours, normalised by the
    reference mask diagonal."""
    def contour_dist(src, dst):
        dt = cv2.distanceTransform((1 - dst).astype(np.uint8),
                                   cv2.DIST_L2, 3)
        edges = cv2.Canny((src * 255).astype(np.uint8), 50, 150) > 0
        vals = dt[edges]
        return float(vals.mean()) if vals.size else 0.0
    diag = _mask_diagonal(a)
    if diag <= 0:
        return 0.0
    return (contour_dist(a, b) + contour_dist(b, a)) / 2.0 / diag


def _mask_diagonal(mask: np.ndarray) -> float:
    ys, xs = np.nonzero(mask)
    if len(xs) == 0:
        return 0.0
    w = xs.max() - xs.min() + 1
    h = ys.max() - ys.min() + 1
    return float(math.hypot(w, h))


def _feature_alignment(ref_rgb: np.ndarray, render_rgb: np.ndarray,
                       mask: np.ndarray) -> Optional[float]:
    """Mean symmetric nearest-neighbour distance between internal edge
    points (Canny edges restricted to the mask interior), in pixels."""
    kernel = np.ones((5, 5), np.uint8)
    inner = cv2.erode(mask, kernel, iterations=2)

    def edges(img):
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) if img.ndim == 3 else img
        e = cv2.Canny(gray, 60, 160) > 0
        return np.logical_and(e, inner > 0)

    ea, eb = edges(ref_rgb), edges(render_rgb)
    if ea.sum() < 10 or eb.sum() < 10:
        return None

    def mean_nn(src, dst):
        dt = cv2.distanceTransform((~dst).astype(np.uint8), cv2.DIST_L2, 3)
        return float(dt[src].mean())
    return (mean_nn(ea, eb) + mean_nn(eb, ea)) / 2.0


def _color_agreement(ref_rgb: np.ndarray, render_rgb: np.ndarray,
                     mask: np.ndarray) -> Optional[float]:
    m = mask > 0
    if m.sum() < 10:
        return None
    diff = np.abs(ref_rgb.astype(np.float32) -
                  render_rgb.astype(np.float32)).mean(axis=2)
    return float(1.0 - diff[m].mean() / 255.0)


def _perceptual_similarity(ref_rgb: np.ndarray, render_rgb: np.ndarray,
                           mask: np.ndarray) -> Optional[float]:
    a = cv2.cvtColor(ref_rgb, cv2.COLOR_BGR2GRAY).astype(np.float64) / 255.0
    b = cv2.cvtColor(render_rgb, cv2.COLOR_BGR2GRAY).astype(np.float64) / 255.0
    m = mask > 0
    a = np.where(m, a, 0.0)
    b = np.where(m, b, 0.0)
    try:
        from skimage.metrics import structural_similarity as ssim
        return float(ssim(a, b, data_range=1.0))
    except Exception:
        pass
    # fallback: masked normalised correlation
    av, bv = a[m], b[m]
    if av.size < 10 or av.std() < 1e-9 or bv.std() < 1e-9:
        return None
    r = float(np.corrcoef(av, bv)[0, 1])
    return max(0.0, min(1.0, r))


def _depth_correlation(ref_depth: Optional[np.ndarray],
                       render_depth: np.ndarray,
                       mask: np.ndarray) -> Optional[float]:
    if ref_depth is None:
        return None
    if ref_depth.shape != render_depth.shape:
        ref_depth = cv2.resize(ref_depth, (render_depth.shape[1],
                                           render_depth.shape[0]),
                               interpolation=cv2.INTER_NEAREST)
    a = ref_depth.astype(np.float64)
    b = render_depth.astype(np.float64)
    m = mask > 0
    if m.sum() < 10:
        return None
    av, bv = a[m], b[m]
    if av.std() < 1e-9 or bv.std() < 1e-9:
        return None
    return float(np.corrcoef(av, bv)[0, 1])


# ---------------------------------------------------------------------------
# overlays
# ---------------------------------------------------------------------------

def _write_overlay(ref_rgb: np.ndarray, render_rgb: np.ndarray,
                   path: Path) -> None:
    h, w = ref_rgb.shape[:2]
    render_rgb = cv2.resize(render_rgb, (w, h))
    blend = cv2.addWeighted(ref_rgb, 0.5, render_rgb, 0.5, 0.0)
    top = np.hstack([ref_rgb, render_rgb])
    label_bar = np.zeros((28, top.shape[1], 3), np.uint8)
    cv2.putText(label_bar, "reference", (10, 20), cv2.FONT_HERSHEY_SIMPLEX,
                0.6, (255, 255, 255), 1)
    cv2.putText(label_bar, "render", (w + 10, 20), cv2.FONT_HERSHEY_SIMPLEX,
                0.6, (255, 255, 255), 1)
    out = np.vstack([label_bar, top, np.hstack([blend, blend])])
    cv2.imwrite(str(path), out)


def _write_silhouette_comparison(ref: np.ndarray, render: np.ndarray,
                                 path: Path) -> None:
    h, w = ref.shape
    out = np.zeros((h, w, 3), np.uint8)
    both = np.logical_and(ref, render)
    ref_only = np.logical_and(ref, 1 - render)
    render_only = np.logical_and(render, 1 - ref)
    out[both > 0] = (180, 180, 180)
    out[ref_only > 0] = (0, 255, 0)       # green: missing in render
    out[render_only > 0] = (255, 0, 255)  # magenta: extra in render
    cv2.imwrite(str(path), out)


def _write_depth_comparison(ref_depth: Optional[np.ndarray],
                            render_depth: np.ndarray, mask: np.ndarray,
                            path: Path) -> None:
    h, w = render_depth.shape
    rd = render_depth.astype(np.float32)
    if rd.max() > rd.min():
        rd = (rd - rd.min()) / (rd.max() - rd.min())
    rd = np.where(mask > 0, rd, 0.0)
    right = cv2.applyColorMap((rd * 255).astype(np.uint8), cv2.COLORMAP_VIRIDIS)
    if ref_depth is None:
        # honest proxy: distance transform of the reference mask
        proxy = cv2.distanceTransform(mask.astype(np.uint8), cv2.DIST_L2, 5)
        if proxy.max() > 0:
            proxy = proxy / proxy.max()
        left = cv2.applyColorMap((proxy * 255).astype(np.uint8),
                                 cv2.COLORMAP_VIRIDIS)
    else:
        a = ref_depth.astype(np.float32)
        a = cv2.resize(a, (w, h), interpolation=cv2.INTER_NEAREST)
        if a.max() > a.min():
            a = (a - a.min()) / (a.max() - a.min())
        a = np.where(mask > 0, a, 0.0)
        left = cv2.applyColorMap((a * 255).astype(np.uint8),
                                 cv2.COLORMAP_VIRIDIS)
    cv2.imwrite(str(path), np.hstack([left, right]))


def _encode_turntable(frames_dir: Path, out_path: Path) -> bool:
    frames = sorted(frames_dir.glob("tt_*.png"))
    if not frames:
        return False
    first = cv2.imread(str(frames[0]))
    if first is None:
        return False
    h, w = first.shape[:2]
    w, h = w - (w % 2), h - (h % 2)   # mp4 needs even dims
    vw = cv2.VideoWriter(str(out_path), cv2.VideoWriter_fourcc(*"mp4v"),
                         12.0, (w, h))
    if not vw.isOpened():
        return False
    for f in frames:
        img = cv2.imread(str(f))
        if img is None:
            continue
        vw.write(cv2.resize(img, (w, h)))
    vw.release()
    return out_path.exists() and out_path.stat().st_size > 0


# ---------------------------------------------------------------------------
# main entry
# ---------------------------------------------------------------------------

def validate_reconstruction(manifest: BlenderManifest, plan: ConstructionPlan,
                            seg: SegmentationResult, crop_meta: CropMetadata,
                            project_dir: str, cfg: PipelineConfig
                            ) -> ValidationResult:
    project = Path(project_dir).resolve()
    val_dir = project / "validation"
    val_dir.mkdir(parents=True, exist_ok=True)
    result = ValidationResult()

    if not manifest.success:
        result.passed = False
        result.notes.append("blender build failed; skipping render validation")
        result.notes.extend(manifest.errors[:3])
        return result

    # ---- reference data ------------------------------------------------
    mask_img = cv2.imread(seg.mask_path, cv2.IMREAD_GRAYSCALE)
    if mask_img is None:
        raise FileNotFoundError("segmentation mask not found: %s" % seg.mask_path)
    ref_mask = _binarize(remap_to_crop(mask_img, crop_meta))
    rgba = cv2.imread(seg.rgba_path, cv2.IMREAD_COLOR)
    if rgba is not None:
        ref_rgb = remap_to_crop(rgba, crop_meta, cv2.INTER_LINEAR)
    else:
        ref_rgb = cv2.cvtColor(ref_mask * 255, cv2.COLOR_GRAY2BGR)

    # ---- render passes via Blender --------------------------------------
    script_path = generate_render_script(plan, ref_mask, str(project), cfg)
    render_manifest = runner.run_blender(script_path, str(project), cfg)
    if not render_manifest.success:
        result.passed = False
        result.notes.append("render script failed")
        result.notes.extend(render_manifest.errors[:2])
        return result

    def load(name, flags=cv2.IMREAD_COLOR):
        img = cv2.imread(str(val_dir / name), flags)
        if img is None:
            raise FileNotFoundError("expected render missing: %s" % name)
        return img

    render_sil = _binarize(load("render_silhouette.png", cv2.IMREAD_GRAYSCALE))
    clay = load("render_clay.png")
    shaded = load("render_shaded.png")
    depth_img = load("render_depth.png", cv2.IMREAD_UNCHANGED)
    if depth_img.ndim == 3:
        depth_img = cv2.cvtColor(depth_img, cv2.COLOR_BGR2GRAY)
    depth_f = depth_img.astype(np.float32) / (65535.0 if depth_img.dtype ==
                                              np.uint16 else 255.0)

    if render_sil.shape != ref_mask.shape:
        render_sil = cv2.resize(render_sil, (ref_mask.shape[1],
                                             ref_mask.shape[0]),
                                interpolation=cv2.INTER_NEAREST)
    shaded = cv2.resize(shaded, (ref_mask.shape[1], ref_mask.shape[0]))
    clay_gray = cv2.cvtColor(clay, cv2.COLOR_BGR2GRAY)
    clay_mask = _binarize(cv2.resize(clay_gray, (ref_mask.shape[1],
                                                 ref_mask.shape[0])), 20)

    union_mask = np.logical_or(ref_mask, render_sil).astype(np.uint8)

    # ---- metrics --------------------------------------------------------
    metrics = ValidationMetrics()
    metrics.silhouette_iou = _iou(ref_mask, render_sil)
    metrics.clay_silhouette_iou = _iou(ref_mask, clay_mask)
    metrics.contour_chamfer_distance = _chamfer(ref_mask, render_sil)
    metrics.feature_alignment_error_px = _feature_alignment(
        ref_rgb, shaded, union_mask)
    metrics.color_region_agreement = _color_agreement(
        ref_rgb, shaded, np.logical_and(ref_mask, render_sil).astype(np.uint8))
    metrics.perceptual_similarity = _perceptual_similarity(
        ref_rgb, shaded, union_mask)

    depth_path = project / "geometry" / "depth.png"
    ref_depth = None
    if depth_path.exists():
        rd = cv2.imread(str(depth_path), cv2.IMREAD_UNCHANGED)
        if rd is not None:
            if rd.ndim == 3:
                rd = cv2.cvtColor(rd, cv2.COLOR_BGR2GRAY)
            ref_depth = rd.astype(np.float32)
            if ref_depth.max() > 0:
                ref_depth = ref_depth / ref_depth.max()
    depth_resized = cv2.resize(depth_f, (ref_mask.shape[1], ref_mask.shape[0]))
    metrics.depth_correlation = _depth_correlation(
        ref_depth, depth_resized,
        np.logical_and(ref_mask, render_sil).astype(np.uint8))

    # ---- artifacts ------------------------------------------------------
    overlay_path = val_dir / "reference_overlay.png"
    _write_overlay(ref_rgb, shaded, overlay_path)
    result.overlay_path = str(overlay_path)

    sil_path = val_dir / "silhouette_comparison.png"
    _write_silhouette_comparison(ref_mask, render_sil, sil_path)
    result.silhouette_comparison_path = str(sil_path)

    depth_cmp_path = val_dir / "depth_comparison.png"
    _write_depth_comparison(ref_depth, depth_resized, ref_mask, depth_cmp_path)
    result.depth_comparison_path = str(depth_cmp_path)

    tt_path = val_dir / "turntable.mp4"
    if _encode_turntable(val_dir / "turntable_frames", tt_path):
        result.turntable_path = str(tt_path)
    else:
        result.notes.append("turntable.mp4 could not be encoded")

    SchemaIO.save_json(metrics, val_dir / "metrics.json")

    result.metrics = metrics
    target = cfg.refinement.target_silhouette_iou
    result.passed = (metrics.silhouette_iou or 0.0) >= target
    if not result.passed:
        result.notes.append(
            "silhouette_iou %.3f below target %.3f"
            % (metrics.silhouette_iou or 0.0, target))
    return result
